project_id = "twwnovstkvhpoxvjrnwn"

[api]
enabled = true
port = 54321
schemas = ["public", "graphql_public"]
extra_search_path = ["public", "extensions"]
max_rows = 1000

[functions.analyze-step-up]
verify_jwt = false
